### ISSUE TITLE
Hide some options from the matrix

### ISSUE THREAD

**Issue by willcastillo** [lara-zeus/matrix-choice#13]
Hello,

Is it possible to, somehow, hide an option from the matrix? Here's my use case:

I have, say, 6 resources I'll be listing as rows and they all have potential actions as columns: C, R, U, D.

Now let's imagine that two out of those six have special actions like -say- MANAGE and APPROVE.

Is it possible to have C, R, U, D, M, A as the columns but not showing the checkboxes/radio on specific rows?

**Comment by atmonshi** [comment]
so since `Matrix` already extending `CheckboxList`, there is a method `disableOptionWhen`
and the result like this by default:

<img width="1070" alt="Screenshot 2024-09-04 at 3 09 12 PM" src="https://github.com/user-attachments/assets/843e7313-8cb6-4fb8-97dc-11bd89a826c0">

so the question is are you planing to disable the "Approve" for example on all resources or specific ones?!

if I made a PR can you Test around!

**Comment by willcastillo** [comment]
That was quick! Thanks lot!

My specific use case, specific ones. I.e.- in your example, image that you can approve customers and companies but not users. The checkbox for users should be visible and enabled.

**Comment by atmonshi** [comment]
whatever conditions you pass. here I am disabling the `m,p` on `users`

```php
->disableOptionWhen(fn (string $value): bool => $value === 'm' || $value === 'p' || $value === 'users')
```

<img width="1067" alt="Screenshot 2024-09-04 at 7 12 27 PM" src="https://github.com/user-attachments/assets/d0f9f794-ba5a-4078-b466-eeab7ffa117a">

you can test the PR #14

**Comment by willcastillo** [comment]
Thanks a bunch @atmonshi !

**Comment by khalidauer** [comment]
Hi there!
Thank you for this awesome package and feature! However, I have one question:

In order to determine whether I can enable/disable the option, I need both values for the given checkbox (e.g. users/manage)

But `string $value` only returns one value.
How can I archive this?

Kind regards

**Comment by atmonshi** [comment]
thank you.
that string is the key for all the matrix
you would do something like this:

```php
->disableOptionWhen(fn (
    string $value
): bool => $value === 'm' || $value === 'p' || $value === 'users')
```
you can check the [demo](https://demo.test/admin/components-demo/matrix) and the code [here](https://github.com/lara-zeus/demo/blob/v3/app/Filament/Pages/Matrix.php)

feel free to open a new issue if you have more questions

**Comment by khalidauer** [comment]
No, what I mean I need the x and y value of the cell to determine if it should be disabled:
    1  2  3  4
A
B
C                 x
D

To determine whether I want to disable C3 I need both values. C and 3. Not just C or just 3.

**Comment by atmonshi** [comment]
you can group your conditions to get the exact same results. maybe I'll look into it after filament v4. currently we freaz any new features.

**Comment by khalidauer** [comment]
Can you make an example for me please? How do I group it?
