### ISSUE TITLE
Checked Option

### ISSUE THREAD

**Issue by Dr-Maspix** [lara-zeus/matrix-choice#6]
Hello Dear , 

Thanks for your work ,
i need to know if i have old values and i need to make checked attribute for some input,
how i can make some of radio checked ? .

Regards

**Comment by atmonshi** [comment]
hey, I wish if you shard some code and where are you using this
in a resource or a page
by default the "edit" should work and fill the values from your DB

but giving the following example you can set the values using `formatStateUsing` like this

```php
Matrix::make('question')
      ->asCheckbox()
      ->formatStateUsing(fn()=>[
          'sat'=>['one'=>true],
          'sun'=>['two'=>true],
          'mon'=>['three'=>true],
      ])
      ->columnData([
          'one'=>'One Item',
          'two'=>'Two Item',
          'three'=>'Three Item',
      ])
      ->rowData([
          'sat' => 'Saturday',
          'sun' => 'Sunday',
          'mon' => 'Monday',
      ]),
```

**Comment by atmonshi** [comment]
if you have values without keys:

```php
->formatStateUsing(fn()=>[
        [0=>true],
        [1=>true],
        [2=>true],
    ])
    ->columnData([
        'one',
        'two',
        'three',
    ])
    ->rowData([
        'sat',
        'sun',
        'mon',
    ])
```

and you can always `dd()` the form and see how the array is structured

**Comment by Dr-Maspix** [comment]
Dear, 
Thanks For Your Replay , 
here is my code , 
![image](https://github.com/lara-zeus/matrix-choice/assets/44633806/d7d13840-2987-4526-b7cd-b929fe753286)

can you feed me back please ,

**Comment by Dr-Maspix** [comment]
i will try with your feed back ,
and i will feed you back , 

Thanks Again <3

**Comment by Dr-Maspix** [comment]
Dear, 
it's working With this way , 

![image](https://github.com/lara-zeus/matrix-choice/assets/44633806/9687394b-468c-4c61-a0af-649777f21881)

![image](https://github.com/lara-zeus/matrix-choice/assets/44633806/dc6560a6-cd1f-4041-bf08-fc4f224ef8be)


but how i can get pass my old values with ->currentData([]) 

like be this 

->currentData([             // This Is My Old Choices Or On In Edit Step
                                            'Question One',
                                            'Question Five',
                                        ]),
                                        
                                        
Best Regards

**Comment by atmonshi** [comment]
in this case you should try use key values to store the data
the:
'Question One',
'Question Five',

is the labels not the values
and it all depend how you store the data

**Comment by Dr-Maspix** [comment]
Thanks Dear,
i will try and feed you back , 
i like your code 

Regards

**Comment by Dr-Maspix** [comment]
Dear,

Kindly please help me and feed me back , 
is there is any wat to make radio checked from blade file ? 
this is your code , 
can you tell me please ? 

![image](https://github.com/lara-zeus/matrix-choice/assets/44633806/c091826f-4a1e-4622-8edc-e235b23fbd5e)

the issue here with ->formatStateUsing()
it's working , 
but i can't control code ,
